server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:65beba6603e2832600884258b802c77b03842caffb88ddba414dca6221d83a3b}
      expiration-time: ${JWT_EXPIRATION_TIME:525960}
  application:
    name: ${SPRING_APPLICATION_NAME:ds-service}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: ${SPRING_JACKSON_TIMEZONE:America/Tijuana}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: ${SPRING_JPA_TIMEZONE:America/Tijuana}

  servlet:
    session:
      cookie:
        http-only: true
        secure: ${SPRING_SESSION_COOKIE_SECURE:false}
