server:
  port: 8080
  servlet:
    context-path: "/api"



spring:
  security:
    token-secret: 65beba6603e2832600884258b802c77b03842caffb88ddba414dca6221d83a3b
    token-expiration: 525960
  application:
    name: ds-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Tijuana
    mapper:
      default-view-inclusion: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: admin
    password: password
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.jdbc.time_zone: America/Tijuana

  servlet:
    session:
      cookie:
        http-only: true
        secure: false